### ISSUE TITLE
Add IPFessay

### ISSUE THREAD

**Issue by skorokithakis** [ipfs/awesome-ipfs#100]
I just wrote [IPFessay](https://gitlab.com/stavros/IPFessay), which is an app that lives fully on IPFS and lets you publish uncensorable essays. I'd appreciate it if you could link to it!

**Comment by VictorBjelkholm** [comment]
Looks cool, if you could submit a PR we'll add it

**Comment by VictorBjelkholm** [comment]
Closed with 46ba41344307aa059cea135822f505f3c55217aa

**Comment by Cam-B** [comment]
IPFessay is awesome.

**Comment by skorokithakis** [comment]
*You*'re awesome!

**Comment by Cam-B** [comment]
;) I've pinned your latest version and am featuring a live version at [Odat.xyz](http://odat.xyz) : [IPFessay](http://odat.xyz:8080/ipns/QmSWnBwMKZ28tcgMFdihD8XS7p6QzdRSGf71cCybaETSsU/)

Keep up the good work please. :) I love how its a file uploader too. IPFessay is a wonderful GUI extension for any IPFS user.

**Comment by skorokithakis** [comment]
Thank you! Props to @stelabouras for the hard work.

**Comment by stelabouras** [comment]
Awww, you are welcome! ❤
