### ISSUE TITLE
Add https://decentralized.cloud/

### ISSUE THREAD

**Issue by alexsicart** [ipfs/awesome-ipfs#111]
https://decentralized.cloud/ Decentralized Cloud enables users to quickly and easily transfer large files of any format using IPFS.

**Comment by RichardLitt** [comment]
PRs accepted!

**Comment by alexsicart** [comment]
@RichardLitt cool

**Comment by RichardLitt** [comment]
(And they're really encouraged. I came here and cleaned up the issues today because I expected to see a decentralized.cloud link. Add one for me! :D )

**Comment by jorge-sanz** [comment]
Fixed in #114 @RichardLitt

**Comment by RichardLitt** [comment]
Merged! Thanks!
