### ISSUE TITLE
Add IPFS Whitepaper

### ISSUE THREAD

**Issue by dimarconicola** [ipfs/awesome-ipfs#113]
https://github.com/ipfs/ipfs/blob/master/papers/ipfs-cap2pfs/ipfs-p2p-file-system.pdf?raw=true

**Comment by hacdias** [comment]
I don't know if the white paper fits the description of Awesome IPFS. Yes, it's awesome, but it's also its foundation and not something built upon it. So I'm not quite sure if we can add it here. What do you think @koalalorenzo?

**Comment by Zippersk** [comment]
Add official white paper or remove the [unofficial white paper (https://decentralized.blog/understanding-the-ipfs-white-paper-part-1.html). I am new to ipfs stuff, found this repo, and thought that the unofficial one is official.

**Comment by hacdias** [comment]
Well, that link is for an article explaining the white paper, not the white paper itself. And they link to the official whitepaper.
