### ISSUE TITLE
Broken link for 'SnapCloud'

### ISSUE THREAD

**Issue by sudo-suhas** [ipfs/awesome-ipfs#122]
If I click on the link, it tries to open https://github.com/ipfs/awesome-ipfs/blob/master/decentralized.cloud. If I manually open `decentralized.cloud` in the browser, it redirects to https://filenation.io/. So change the link to https://filenation.io/ or is 'SnapCloud' something else?

**Comment by koalalorenzo** [comment]
I would wait a little bit just in case they change the name again 😆 
JK! filenation should be the right one for now

**Comment by hacdias** [comment]
Closing this as SnapCloud is not on our list anymore 😄 And File Nation also seems offline.
