### ISSUE TITLE
Make ipfs/awesome-ipfs into a static site

### ISSUE THREAD

**Issue by VictorBjelkholm** [ipfs/awesome-ipfs#126]
So, we're starting to have a lot of items here that are a bit dis-organized and not very pretty to look at neither discoverable.

I propose we add Hugo to this repository and move all the listens to a data file (yml/toml/json format) and then build a html page that we can deploy on `awesome.ipfs.io` or something like that + to update the listing in the readme.

What do people think about this?

**Comment by jnv** [comment]
To be honest, I'd recommend against this. I saw a few lists to take this route and the end result was overengineered and much less approachable for contributors. For example [alternative-internet](https://github.com/redecentralize/alternative-internet) turned all its items into JSON and after a few years of struggling there is now proposal to return back to the simple, single README.md file. I personally like approach similar to [awesome-electron](https://github.com/sindresorhus/awesome-electron): the MD list is parsed, reformatted and displayed on [Electron's site](https://electronjs.org/community).

**Comment by VictorBjelkholm** [comment]
Thanks @jnv for the input, the approach of parsing the markdown lists feels like a good middle-ground and not too difficult. Guess problem becomes with that I'd like to include a picture/GIF, some tags and other metadata about it, and a list might be too messy.

This issue was also mentioned during yesterdays all-hands, as more and more people are looking for a gallery of applications/libraries using IPFS in the wild.

**Comment by jnv** [comment]
@VictorBjelkholm I understand, plain readme file is not very appealing for end users and has quite some limitations.

I think there might be space for both approaches and the aforementioned Electron seems like a good example to me. Besides the awesome-electron list, there is also the [apps catalog](https://github.com/electron/electron-apps) with each entry as a directory with YAML, icon and other assets. So while the apps catalog presents the end user products built on platform, the awesome list is more developer oriented and gives a bigger picture about the whole ecosystem.

**Comment by hacdias** [comment]
Hello! 😄 In the beginning of this quarter, we (the IPFS In Web Browser working group) set as key results this:

- Publish 3 documented (code-annotated) example apps
- Create a catalog of window.ipfs experiments similar to https://experiments.withgoogle.com/chrome

In the meanwhile, @VictorBjelkholm reminded us, during our weekly sync on IRC, we came to the conclusion that we should add those example apps to a section on this repo and use this repo as a source of truth for a website where we could showcase examples of IPFS apps.

> @lidel: if we add tags to awesome-ipfs  somehow, that will make things super easy to share (eg. share demos that use window.ipfs, share)

This was just a quick update, and I'm waiting to get feedback from everyone. I had two ideas:

- Or try to do what @lidel said;
- Or we could create a static website (with Hugo) and use ["Data folder"](https://gohugo.io/templates/data-templates/) to gather the info and with it we could build the website **and** we could have a simple script to create this repo's README based on that info. That way it would be easier to build the website, but I'm sure we could do it in the other way around.

/cc @olizilla @alanshaw @lidel @diasdavid @akrych

**Comment by olizilla** [comment]
Yep, I'd go with a static site, with "generated readme" as a nice to have, but not urgent secondary goal. 

More generally I fully agree with the plan of "lets have both!" a nice public site, and an up-to-date README.

**Comment by VictorBjelkholm** [comment]
Notes published here: https://github.com/ipfs/awesome-ipfs/pull/130/files#diff-63d64c61b0a30fb30dcadfbaac2823c1

**Comment by VictorBjelkholm** [comment]
Fixed in 9f0bbeb
