### ISSUE TITLE
Forever - a file sharing and hosting app built on IPFS

### ISSUE THREAD

**Issue by UnsignedInt8** [ipfs/awesome-ipfs#128]
Hi, guys. I've developed a file sharing app, please see [https://ipfs-forever.github.io](https://ipfs-forever.github.io). The source code is [here](https://github.com/unsignedint8/forever). 

![home](https://user-images.githubusercontent.com/15274326/37071256-a389cee8-21f6-11e8-905d-3ec2543da1ec.jpg)

![files](https://user-images.githubusercontent.com/15274326/37071262-aae13faa-21f6-11e8-96a6-fcf06a74c004.jpg)

**Comment by lidel** [comment]
Hey, its really cool! 

I glanced at sources and I noticed use of service worker, and `orbit-db`.  
What problems solved with each of them?

**Comment by dryajov** [comment]
This would be killer if we could have some sort of authentication scheme (and encryption), so that I can access my files from anywhere...

**Comment by UnsignedInt8** [comment]
@lidel I tried to use orbit-db to sync data between devices, but not in current version.

**Comment by lidel** [comment]
@UnsignedInt8 sync would be an awesome feature :+1:  Make sure to post an update here when that lands  and create a PR to this repo if you want your app to be added to the list.

**Comment by UnsignedInt8** [comment]
@lidel Thanks.
