### ISSUE TITLE
Java-IPFS-Client

### ISSUE THREAD

**Issue by hazae41** [ipfs/awesome-ipfs#129]
Hello, please add my software Java-IPFS-Client, it is a lightweight IPFS client written in Java (portable to every computer)

Link: https://github.com/RHazDev/Java-IPFS-Client

**Comment by hacdias** [comment]
Closing as the repository doesn't exist anymore. Also, my sincere apologies for no one getting back to you here, @hazae41!

Also, I'd like to mention that there seems to be a Java HTTP Client for IPFS: https://github.com/ipfs/java-ipfs-http-client.
