### ISSUE TITLE
xfce-screenshooter with IPFS support!

### ISSUE THREAD

**Issue by amar-laksh** [ipfs/awesome-ipfs#143]
[xfce-screenshooter-ipfs-support](https://github.com/amar-laksh/xfce-screenshooter-ipfs-support) - A fork of xfce-screenshooter with IPFS upload support!(no native ipfs-nodes required!).

**Comment by hacdias** [comment]
Hello @amar-laksh! Sorry for taking... a year to reply to you. I'm taking a look at all the backlog we have here. Does it still work? Is it still updated? How does it work?

/cc @koalalorenzo

**Comment by amar-laksh** [comment]
Oh man, I had totally forgotten about it. So I did build and check it again. Everything seems to work fine. :)

**Comment by hacdias** [comment]
Well, you actually added this 8 months ago! We just forgot to close this issue. Please see cc4e2644a3c158726c926699761fe54745bfb1a2 😃 Sorry for that!
