### ISSUE TITLE
Deploy ipfs-companion demos and list them here

### ISSUE THREAD

**Issue by daviddias** [ipfs/awesome-ipfs#144]
@alanshaw can we follow up on deploying all the demos to IPFS and link them from a friendly URL so that we can share them here? //cc @VictorBjelkholm  for deployment

**Comment by alanshaw** [comment]
The demos are (notes for me really):

https://github.com/tableflip/ipfs-peer-bw-example
https://github.com/tableflip/ipfs-pubsub-chat-example
https://github.com/tableflip/ipfs-peer-map-example

I can handle the deploy to IPFS and pin (I'll post back here when they're done).

The friendly URL DNS stuffs I need help with ;)

**Comment by VictorBjelkholm** [comment]
If we'd want automatic deployment they would have to live within one of our orgs, like ipfs-shipyard. Can we possibly move them there?

**Comment by alanshaw** [comment]
Sure, I'll move them to shipyard - any opinions on the repo names? I was thinking "demo" might be better than "example"...and we should prefix with "js-" right?

**Comment by diasdavid** [comment]
@alanshaw 👍 on `demo` and no need for `js-`. We only use the { `js-`, `go-`, `language-` } prefix to make it clear when it is a piece of a protocol built on a specific language. Apps and Demos can have their own name :)

**Comment by hacdias** [comment]
@alanshaw I also built these two demos some time ago for companion. Are they worth moving?

https://github.com/hacdias/ipfs-todo
https://github.com/hacdias/ipfs-id-qr-codes

**Comment by alanshaw** [comment]
Yep!

**Comment by VictorBjelkholm** [comment]
On second thought, does it make sense to have one "demo" repository where we can at least pull in the various demos (or at most let the demos live in general)? Rather than having a website per demo, we would have one website showing all the demos (of course only loading the resources for the demo once navigated there).

**Comment by hacdias** [comment]
I agree with @VictorBjelkholm. If you agree @alanshaw I can create the repository and we can move the repos there, keeping the commit history if possible 😄

**Comment by koalalorenzo** [comment]
As an external to protocol labs I find very confusing and dispersive all this structure in different repositories. Please, consider what other people outside may find useful and the accessibility of the content you want to showcase.

Are the demo awesome? IMHO they should be here :)

**Comment by hacdias** [comment]
@koalalorenzo what would you find easier and more practical? Multiple `demo-` repositories or one `demos` repository with all demos.

**Comment by alanshaw** [comment]
It'll be a whole bunch of work add our demos to a single repo and to orchestrate the various build steps to get a single site built.

Is there a way we can setup a syndicate website where we can alias `demos.ipfs.io/[mydemo]` to `QmHash`? Or even on this site - `awesome.ipfs.io/demos/[mydemo]`.

For the future when we have base32 support and the gateway has been updated, it would be cool if jenkins could add/update a CNAME record for a given domain to point mycname.demos.ipfs.io to bafyhash.ipfs.io as part of a deploy process.

**Comment by koalalorenzo** [comment]
@hacdias reuse this repository with a new category for demos! :D

**Comment by hacdias** [comment]
Added the two other demos: https://github.com/ipfs/awesome-ipfs/pull/180

**Comment by hacdias** [comment]
I'm closing this as ipfs-companion demos are already listed in the website.
