### ISSUE TITLE
Merge the PR

### ISSUE THREAD

**Issue by koalalorenzo** [ipfs/awesome-ipfs#147]
Hey guys! 
Is anybody having a look at the PR?
There are some that are still waiting and the changes are not that complex... :)

**Comment by koalalorenzo** [comment]
@Mr0grog, @VictorBjelkholm Is help needed?
I could help managing this repository if it is hard!

**Comment by VictorBjelkholm** [comment]
So, there are two reasons why PRs are pending. First reason is that the changes are small, but they need to be reviewed to make sure the thing is actually "awesome" by some definition. So we can't just merge stuff, has to actually review them.

Second reason is that we're currently working on reorganizing the information in this repository, to have some better discoverability, but that's more minor.

**Comment by koalalorenzo** [comment]
Awesome! Thank you!
