### ISSUE TITLE
Let's make awesome-ipfs more awesome!

### ISSUE THREAD

**Issue by diasdavid** [ipfs/awesome-ipfs#148]
We have a ton of new demos, tutorials, apps and posts to share.

**Comment by diasdavid** [comment]
Seems that @hacdias beat me to it

![image](https://user-images.githubusercontent.com/1211152/42750201-a85f350a-88e6-11e8-98c4-749dbb39b9b2.png)

Is this page deployed somewhere?

**Comment by VictorBjelkholm** [comment]
@diasdavid let us finish the page, then we deploy it :) It's coming there. 

Can you add a list or something of the things you'd like to add? Right now this issue is not very actionable as it is

**Comment by diasdavid** [comment]
Yeah, @hacdias had a foresight and built what I wanted <3

**Comment by diasdavid** [comment]
Yeah, @hacdias had a foresight and built what I wanted even before I knew it! ❤️
