### ISSUE TITLE
Label existing projects

### ISSUE THREAD

**Issue by victorb** [ipfs/awesome-ipfs#151]
Now we have a website! But many of the awesome projects don't have any labels. We should try to come up with a taxonomy and label all of them, then make sure the search and navigation between labels work.

**Comment by hacdias** [comment]
It could be tags, for example. We just need to add them to the .yaml files and render them into the cards. Everything else will just work (navigation included).

**Comment by VictorBjelkholm** [comment]
Ah, yeah, tags/labels. As long as the labeling works the same way as the categories does (static pages with rendered content). Is that true already?

**Comment by hacdias** [comment]
Yes, yes. Just need to add the array of tags to each thing on the data files and add print them (with links) on the cards. Everything else will just work 😄

**Comment by VictorBjelkholm** [comment]
So, going `/tags/app/` works and renders the right items. What's missing is a way of going to that URL without knowing it beforehand.

**Comment by hacdias** [comment]
Adding:

```html
{{ $base := .Site.BaseURL }}
{{- if isset .Params "tags" }}
  <div class="mt2 flex">
    {{ range .Params.tags }}
      <a class="mr1 no-underline monospace charcoal bg-snow dib f7 pa2 br1" href="{{ $base }}/tags/{{ . }}">
        {{- . -}}
      </a>
    {{ end }}
  </div>
{{ end }}
```

To line 56 on ./src/layout/partials/list.html will render a list of the tags and they'll look like badges.

**Comment by hacdias** [comment]
Is this still intended? /cc @koalalorenzo @olizilla

**Comment by 2color** [comment]
Closing this in an effort to reboot this list while keeping the maintainer overhead as low as possible while still making sure the list is awesome! Thanks for your suggestion @victorb
