### ISSUE TITLE
"Featured" label

### ISSUE THREAD

**Issue by victorb** [ipfs/awesome-ipfs#152]
As mentioned before, we should have a "Featured" label that will make the project be first in the ordering within a category or other label.

**Comment by flyingzumwalt** [comment]
This is really important. The default landing state for the static site should be a curated list that puts our best foot forward. Plus, if you implement it with generic tagging where "Featured" is just one tag, we will be able to add other ways to filter & sort over time. But the more important thing is to allow us to mark things as featured.

**Comment by koalalorenzo** [comment]
What should be a condition to be "featured"? 
Should we have it time-based? (ex: Last 10 updates are featured)
Should it be decided by the community based on the votes on the PR?
