### ISSUE TITLE
Make it accessible through awesome.ipfs.io

### ISSUE THREAD

**Issue by diasdavid** [ipfs/awesome-ipfs#155]

**Comment by VictorBjelkholm** [comment]
Final step: https://github.com/ipfs/awesome-ipfs/pull/156

**Comment by hacdias** [comment]
It is!!!! https://awesome.ipfs.io/ 

Thanks @VictorBjelkholm !!!

**Comment by koalalorenzo** [comment]
Should we than update the repository website? (I am talking about the GitHub _header_, right next to the title and tags of the repo )

**Comment by VictorBjelkholm** [comment]
@koalalorenzo yeah, that's a good idea :) Updated it. Thanks everyone!
