### ISSUE TITLE
Update repo description and topics to new non-code repo standards

### ISSUE THREAD

**Issue by Mr0grog** [ipfs/awesome-ipfs#158]
See also ipfs/docs#57

The description here is great, but we should prefix it with either 🤖 or 📚 or both. It should also have the topics `type:website` or `type:documentation` or both.

**Comment by hacdias** [comment]
I guess we'll also need to tweak the navbar to fit those new topics.

**Comment by Mr0grog** [comment]
Oh no, this is about description and topics *on github*, not in the site.

**Comment by Mr0grog** [comment]
We’re trying to make it clear what repos are actually part of the IPFS codebases vs. what’s build infrastructure, web sites, repos used as discussion boards, etc.

**Comment by hacdias** [comment]
Oh, gotcha @Mr0grog 😄 makes sense.

**Comment by hacdias** [comment]
@daviddias perhaps you could fix this, please? I don't have perms to edit the repo.
