### ISSUE TITLE
Show static youtube thumbnails rather than embedding the video

### ISSUE THREAD

**Issue by VictorBjelkholm** [ipfs/awesome-ipfs#163]
For two reasons:

1. Once we have a lot of videos, it'll be too much for a normal PC to render efficiently, thumbnails would be way more performant.

2. YouTube ads their own tracking with embedding, meaning that YouTube can track visitors of the website, while the website is generally tracking-free right now. Replacing embeds with thumbnails would make adblock/privacy extensions should less misleading icons

![image](https://user-images.githubusercontent.com/459764/43317591-a96adf48-919d-11e8-8880-891f695d195e.png)

**Comment by hacdias** [comment]
Agreed! I can do that

**Comment by VictorBjelkholm** [comment]
Awesome work again @hacdias, thanks! :1st_place_medal:
