### ISSUE TITLE
What about a Services section?

### ISSUE THREAD

**Issue by koalalorenzo** [ipfs/awesome-ipfs#168]
I have noticed that some elements that are actually paid-services, are marked as "Apps" or even "tools", but those are nor apps nor tools, but Services (mostly paid).

Should we consider adding a new Services section?

**Comment by hacdias** [comment]
@koalalorenzo it seems some people agree with this. Shall we?

**Comment by autonome** [comment]
+1 to services... there will only continue to be more of them!

**Comment by hacdias** [comment]
Just added a category for services and added Pinata there. If there is any other that you think that qualifies as service, please move it there 😃
