### ISSUE TITLE
Add Projects from IPFS User Registry to awesome-ipfs

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/awesome-ipfs#173]
In the lead-up to the Developer Meetings we asked people to submit information about their projects to an IPFS User Registry. (see [the announcement](https://ipfs.io/blog/37-ipfs-conf-dev-meetings-and-user-registry.md) ). Now that we're able to render awesome-ipfs as a website, let's make sure everyone from the user registry (those who indicated that we can display their info publicly) is listed in awesome IPFS. 

Access to the responses from the User Registry form is restricted. I can pass the necessary info to whoever takes on this task. 

Note: We also have an older informally-build user registry with about 80 projects listed. We should check that one too and see if there are any missing from awesome-ipfs.

**Comment by hacdias** [comment]
@flyingzumwalt what's the state of IPFS User Registry?
