### ISSUE TITLE
Find a nice way of showing hashes for datasets and other things

### ISSUE THREAD

**Issue by victorb** [ipfs/awesome-ipfs#176]
Currently, the hashes are a bit long and breaks the layout a bit when included. It's a shame as we want to show the hash especially for datasets so they are easy to copy-paste/verify manually.

One idea could be to abbreviate the hashes (which we do now) and expand then without having the layout to reflow when hovering over the card (we don't do this currently).

Other ideas are welcome :)

**Comment by lidel** [comment]
cc @ipfs/gui-team  – I imagine coming up with standardized way of  shortening hashes for displaying on smaller spaces/screens will be useful for WebUI and other GUI apps as well :sparkles:

**Comment by hacdias** [comment]
This is solved!
