### ISSUE TITLE
All the new PR are still not populating /data

### ISSUE THREAD

**Issue by koalalorenzo** [ipfs/awesome-ipfs#187]
Even after we made it a little bit more clear to the users in #159, since #130 all the edits on the README have to be made in the `/data` files. This is very much counterintuitive to what the standard `awesome` repositories, and I find it annoying that I have to remember people to do it.

Now I am in solution mode and I should not be: If we could generate the data from the README and enrich it with information/pictures in `/data` it could be a quick win for all the contributors as well as easier to maintain. That is one suggestion. An other one that I had in mind is to decouple the website with this repository and have a scraper taking care of these information.

**Comment by HugoReeves** [comment]
@koalalorenzo I am hoping that #195 will help to resolve this issue.

**Comment by hacdias** [comment]
Hey @koalalorenzo - yes, this is not the best scenario and it seems that people are contributing without even reading the [first section of the README](https://github.com/ipfs/awesome-ipfs#contribute-to-this-list). My suggestion, as @HugoReeves's is to create a PR Template. Maybe that will force people to read it.

**Comment by koalalorenzo** [comment]
I think we can close this now :)
