### ISSUE TITLE
Do we have Analytics? Would love to know how many people are using Awesome IPFS

### ISSUE THREAD

**Issue by daviddias** [ipfs/awesome-ipfs#200]

**Comment by koalalorenzo** [comment]
Should this be public?

**Comment by autonome** [comment]
I've been looking at Fathom - privacy oriented web analytics: https://usefathom.com/

**Comment by hacdias** [comment]
It seems we're now using countly on Web UI and other apps. Should they be added here? /cc @olizilla

**Comment by 2color** [comment]
Closing this as part of an effort to reboot this list while keeping the maintainer overhead as low as possible while still making sure the list is awesome by just using the README.
