### ISSUE TITLE
Add Nebulus and Archivatory

### ISSUE THREAD

**Issue by DonaldTsang** [ipfs/awesome-ipfs#233]
https://github.com/jrswab/nebulus and https://github.com/jrswab/archivatory

**Comment by hacdias** [comment]
@DonaldTsang sorry for taking almost 6 months getting back to you. I see archivatory is offline and the website isn't working, but Nebulus seems up and running! If you're still interested, could you please open a Pull Request [following the guidelines](https://github.com/ipfs/awesome-ipfs/blob/master/CONTRIBUTING.md) so we can publish it?

**Comment by NukeManDan** [comment]
https://nebulus.app seems to be down
