### ISSUE TITLE
Pre-commit hook

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/awesome-ipfs#24]
We should have one for this repo. 

Suggestions of things to check for:
- [ ] 80 char wrap. I don't care, but some people do, not hard to check for.
- [ ] Alphabetized
- [ ] Date checking for articles

Anything else?

**Comment by jbenet** [comment]
My votes, but up to you, not my repo:

- :-1: on 80 char wrap
- :+1: alphabetized
- :+1: date checks

**Comment by RichardLitt** [comment]
Based on my interaction with other lists, I've decided against a gitcop model. It removes the human element of checking things like this for soft lists - sometimes, alphabetizing it isn't as important as lowering the barrier of entry. 

Closing this pending further debate.
