### ISSUE TITLE
Nodesphere.

### ISSUE THREAD

**Issue by jbshirk** [ipfs/awesome-ipfs#25]
https://github.com/nodesphere/nodesphere

Nodesphere is an ambitious project designed to connect the data sources that we care most about into a single unified dashboard:
- Our social networks
- Our curated collections
- Our sense-making information
Nodesphere is a collection of isomorphic visualization-style interfaces. Each interface has particular strengths, so the user can switch between interfaces depending upon the data set and the desired interaction style.

**Semantic Crunching**
Nodesphere uses semantic crunching technology, which reduces data inputs into their atomic semantic nodes. Regardless of the data source, the important knowledge is digested into an interconnected graph, with appropriate connections between tags, categories, peoples' names, etc.

**Open Graph Stack**
The primary interface will be through the visualization layer, which allows filtering, sensemaking and visual navigation of all data (technology: javascript visualization)
- Each individual or organization will have their own instance of a graph server, to store relationships between their most used data (technology: graph database)
- All data may optionally be reflected to permanent distributed storage layers (technology: IPFS)

**Status**
Nodesphere is in active development, focussing on:
- Multiple visualization interfaces
- Morphing between visualizations
- Reading data from multiple backends, starting with IPFS

**Comment by RichardLitt** [comment]
Cool! Is there a beta version yet?

**Comment by harlantwood** [comment]
Nope!  Working on it : ) 

Mostly we are focusing on Core Network now:
https://github.com/core-network/core-network
which uses Nodesphere under the hood...  

Thanks for noticing!  We'll keep you posted on progress.

**Comment by RichardLitt** [comment]
Cool. Let's close this until it is up.
