### ISSUE TITLE
In IPFS, a partial change to the original data will generate a new hash. There is a problem here. Is this a reasonable content change or a malicious cheating attack?

### ISSUE THREAD

**Issue by MANHUN** [ipfs/awesome-ipfs#256]
In IPFS, a partial change to the original data will generate a new hash. There is a problem here. Is this a reasonable content change or a malicious cheating attack?

**Comment by hacdias** [comment]
Hey @MANHUN, this isn't related to the topic of this repository. The best would be to ask for that on [discuss.ipfs.io](https://discuss.ipfs.io/)! Certainly there will be more people there capable of answering you.
