### ISSUE TITLE
I want to know how the content of the ipfs network is viewed. Is there a search port like Google?

### ISSUE THREAD

**Issue by MANHUN** [ipfs/awesome-ipfs#257]
I want to know how the content of the ipfs network is viewed. Is there a search port like Google?

**Comment by autonome** [comment]
Here's a thread which has a couple of search engines that index the network:

https://www.reddit.com/r/ipfs/comments/bex0m0/whats_ipsea_ipfs_search_engine/

**Comment by hacdias** [comment]
@MANHUN for this kind of questions, I think you'd be better with our [discourse](https://discuss.ipfs.io/)!
