### ISSUE TITLE
3D IPFS logo using ZDOG!

### ISSUE THREAD

**Issue by drbh** [ipfs/awesome-ipfs#258]
Hey IPFSers

I've remade the IPFS logo in zdog here and thought I should share it with the community. I'm not sure the best location but check out the repo here https://github.com/drbh/ipfs-zdog

![out](https://user-images.githubusercontent.com/9896130/59321231-45c8ff80-8c9f-11e9-8bb0-d5c35e106de7.gif)

**Comment by hacdias** [comment]
@drbh I quite like what you made with the logo and its a nice experiment. Although I'm not sure if it qualifies as a thing to add to this repository. Nice work nevertheless!

/cc @koalalorenzo should we close this?

**Comment by le-dawg** [comment]
If it is an SVG animation it should be the official logo of this repo
