### ISSUE TITLE
The IPFS Ecosystem Diagram

### ISSUE THREAD

**Issue by momack2** [ipfs/awesome-ipfs#304]
The awesome IPFS Ecosystem Diagram, made by the wonderful @akrych, is now open for anyone in the IPFS community to add their own project logo! 
![Frame 1](https://user-images.githubusercontent.com/618519/69945610-c58d9500-149e-11ea-9be8-7429c4d9a201.png)

Given there are more awesome projects using IPFS than we can keep updated, we thought we'd trial making a community-editable version so that everyone can add logos for new projects built on IPFS. This might fail horribly (design by distributed group doesn't always lead to usable outputs), but maybe it will be awesome! We'll let the experiment run for a few months and see how it goes.

Here's the Figma link: https://www.figma.com/file/2bVNnjoOmxh4TtID9kzqEG/IPFS-Applications-Diagram - anyone should be able to copy-and-paste a new logo
 in, and resize/move things around to make it fit. Please try to match existing alignment and sizing where possible! Once you have things added, you can export the image by clicking the hamburger menu > File > Export Frames to PDF.

**Comment by momack2** [comment]
Lots of updates so far!
<img width="1232" alt="Ecosystem Diagram" src="https://user-images.githubusercontent.com/618519/74373908-3819cb80-4d92-11ea-816a-1b6f04002b4c.png">

**Comment by jbenet** [comment]
latest 

![image](https://user-images.githubusercontent.com/138401/87716862-4f574d80-c764-11ea-8272-2482d6a1e300.png)

**Comment by jessicaschilling** [comment]
Is this OK to PR against the ipfs.io website to update this link? 
![image](https://user-images.githubusercontent.com/1507828/87717034-fd66f580-c76c-11ea-99fe-9ffe8cfba5c1.png)

**Comment by momack2** [comment]
Yes please!

**Comment by 0xywzx** [comment]
@momack2  Hi, I'm planning to publish a book about blockchain projects, would it be okay to include this diagram in the book?

**Comment by jessicaschilling** [comment]
@0xywzx - you can actually see the most recently updated version of this here:
https://ecosystem.ipfs.io/showcase/?category=focus
It generates a diagram on demand based on the latest info from the IPFS Ecosystem Directory at https://ecosystem.ipfs.io . Thanks!

**Comment by 0xywzx** [comment]
@jessicaschilling Thank you! This is so helpful!!
I will try to contact them to get permission.

**Comment by 2color** [comment]
Closing this in an effort to reboot this list while keeping the maintainer overhead as low as possible while still making sure the list is awesome!
