### ISSUE TITLE
Clarify policy around content/data - "built with" vs "published on"

### ISSUE THREAD

**Issue by autonome** [ipfs/awesome-ipfs#323]
In #150 we landed a policy for evaluating submissions for what will be added to the site.

While the language makes a clear distinction between IPFS vs other projects (libp2p, Filecoin, etc), it doesn't make a distinction between content published *on* IPFS vs things built *with* IPFS.

While significant and large datasets seem ok, I'm less sure about the value of individual pieces of media being listed only because they are published on IPFS.

Thoughts?

**Comment by RubenKelevra** [comment]
I think we should reevaluate the categories:

-Services build with IPFS somewhere in the background, as 'honorable mention', like Filecoin, Cloudflare-IPFS-Gateway etc.

-Open Source Applications/Services you can run yourself and extend the functionality of IPFS.

-Datasets you can help to provide, which are explained to be static

-Collab-Clusters which you can help to spread, which are explained to be dynamic

-Ressources like Videos, How-Tos, Guides, Documentations, Toolsets etc.

-News Articles (of third parties) covering IPFS directly or a specific service/application running with IPFS in the background.

**Comment by RubenKelevra** [comment]
And we should add a hint that everything found not working for 4 weeks will be removed again.

On software: No development activity for 6 month while no stable has been released.

We have definitely an issue with old stuff collecting in the index.

**Comment by autonome** [comment]
Thanks @RubenKelevra for the feedback - those should be part of different issues however. Feel free to file separately.

This is solely for the built-with vs content question.

**Comment by RubenKelevra** [comment]
> Thanks @RubenKelevra for the feedback - those should be part of different issues however. Feel free to file separately.
> 
> This is solely for the built-with vs content question.

Thanks, I've created #330 :)

**Comment by RubenKelevra** [comment]
> And we should add a hint that everything found not working for 4 weeks will be removed again.
> 
> On software: No development activity for 6 month while no stable has been released.
> 
> We have definitely an issue with old stuff collecting in the index.

This has been filed separately as #325

**Comment by jessicaschilling** [comment]
I'm going to close this and move the discussion into https://github.com/ipfs/awesome-ipfs/issues/367 -- that issue is focusing on what questions go into a "submit your thing" form, and the issue of built with/published on essentially starts there.
