### ISSUE TITLE
Automate updating of readme

### ISSUE THREAD

**Issue by andrew** [ipfs/awesome-ipfs#324]
Currently every contribution requires checking out the repository locally, installing a bunch of npm modules and running the script to update the readme. 

I propose we set up a [github action](https://help.github.com/en/actions) that updates the readme after ever pull request has been merged, that way contributors only need to add the relevant yaml file and optionally add an image.

**Comment by andrew** [comment]
It was also be good to get some kind of CI running against each PR as well to validate that their contributions will build correctly.

**Comment by RubenKelevra** [comment]
I wonder why we need the readme in the repo in the first place. We could just explain how to modify the data of the repo in the readme and link to the website, and a text version of the website instead of adding the text-version again to the repo.

**Comment by jessicaschilling** [comment]
**This issue is one of the prioritized recommendations in the [Q1 2020 IPFS Ecosystem Audit](https://github.com/ipfs/community/tree/master/ecosystem-audit) for execution in Q2/Q3 2020. Tagging it with `$auditrecommendation` means it's searchable! See [all tagged issues](../issues?q=is%3Aissue+%22%24auditrecommendation%22+) in this repo.**

**Comment by jessicaschilling** [comment]
Noted that this needs to be included as part of the functionality of https://github.com/ipfs/awesome-ipfs/issues/366.

**Comment by andrew** [comment]
@jessicaschilling this issue had actually been fixed for months, I would close but seems like a useful point for other work

**Comment by 2color** [comment]
Closing this in an effort to reboot this list while keeping the maintainer overhead as low as possible while still making sure the list is awesome! 

See https://github.com/ipfs/awesome-ipfs/pull/478 for more info
