### ISSUE TITLE
Policy on removing listed projects & content

### ISSUE THREAD

**Issue by NukeManDan** [ipfs/awesome-ipfs#325]
It was mentioned to me at dnsummit.cryptorado.org and ethdenver.com a few times that these listed projects were somewhat stale. Some (from what I have heard) are no longer maintained, and the quality of the projects varies widely. 

I would suggest we add a policy for app and content listings to be automatically removed after something on the order of 6 months at the discretion of the maintainers here based on some criteria we establish;
- no new commits or obvious signs of use and growth of the applications/content listed
- app/content becoming outdated or incorrect.
- other metrics?

Also would suggest in the README, on the awesome.ipfs.io site, the content policy, and CONTRIBUTING that everyone is encouraged to post issues spotting these kind of issues.  

#150 :wave:

**Comment by RubenKelevra** [comment]
We can create Issues for deletions and mention the user account who added the content, to give some chances to recover broken installations, movements of content etc.

After like 30 days we could remove the listing for the content again.

**Comment by NukeManDan** [comment]
we need to make that clear precisely and encourage the community to help with this.

**Comment by RubenKelevra** [comment]
Additionally, I like to keep resources (articles, news, how-tos, videos) cached in the IPFS network, to avoid that stuff gets lost. See https://github.com/ipfs/awesome-ipfs/issues/326

**Comment by momack2** [comment]
I think removing broken/deprecated projects makes sense, but would be sad to see tools that still work (but maybe are no longer a strong focus) being removed. I found a great IPFS markdown tool by searching the old archives that was very useful for me, but I don't think actively under development. Old data (like archives) may still be useful even if not freshly updated too. 

If the bar is "it uses IPFS & functional/exists" - then I think anyone can file a removal issue/PR tagging the initial uploader at any time which will get triaged along with additions. SG?
