### ISSUE TITLE
create a collaborative cluster for ressources

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/awesome-ipfs#326]
We currently list a lot of ressources like articles, videos, howtos etc.

I propose we create a collaborative cluster to hold those ressources and require the users who wants to add ressources to supply a IPFS CID and a original source link for the ressources.

Or we could just use the currently already existing ipfs-website collaborative cluster, and add a subdomain like ressources.awesome.ipfs.io which just contains the ressources.

But this would increase the size of this collaborative cluster significantly.

**Comment by RubenKelevra** [comment]
@hsanjuan what's your opinion on that? Can we grow the `IPFS Websites` cluster?

**Comment by hsanjuan** [comment]
We have a large cluster on which we pin everything and that users can send content to (i.e. using the IRC pinbot), but it is not collaborative. We have plans to migrate it and will open it up then. At that point we will be able to split some large items (wikipedia archives, ccc archives) into their own clusters too, I hope.

**Comment by 2color** [comment]
Closing this in an effort to reboot this list while keeping the maintainer overhead as low as possible while still making sure the list is awesome! 

See https://github.com/ipfs/awesome-ipfs/pull/478 for more info
