### ISSUE TITLE
Move collab.ipfscluster.io into awesome-ipfs

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/awesome-ipfs#327]
Currently, we have datasets in this repo and collab clusters in a [different repo](https://github.com/ipfs-cluster/collab.ipfscluster.io).

How about moving the list of clusters to this repo and changing collab.ipfscluster.io to a guide on how to take part in a cluster to cover the basic stuff, like which options to activate on the ipfs daemon, how to increase the repo size, move the IPFS directory etc.

@hsanjuan opinions? :)

**Comment by hsanjuan** [comment]
I don't see a reason for having to put datasets and the website in a similar place. Right now I don't have time to rethink, re-do that website's design, so I guess it's going to stay as it is for the moment.

**Comment by RubenKelevra** [comment]
@hsanjuan the current list of 4 items can easily be kept on two places, but when the list gets exausting we probably want to maintain it in one place.

I feel like the right place is [awesome IPFS](https://awesome.ipfs.io/) which offers a searchable user interface which shows it not only to users interested in replication but also interested in browsing the replicated data.

Currently the website can stay as-is IMHO and I would create a new category in awesome-ipfs to see how it gets accepted by the user and work out in practice. We'll keep this ticket open until we decided what to do and track the progress.

How does this sound? 🤔

**Comment by hsanjuan** [comment]
Sorry, I understand better now. The datasets here are static, while cluster ones are meant to be more dynamic, but yeah we should probably merge things somehow (i.e. if a cluster is available for a dataset, it should show instructions on how to join).

**Comment by 2color** [comment]
Closing this in an effort to reboot this list while keeping the maintainer overhead as low as possible while still making sure the list is awesome! 

See https://github.com/ipfs/awesome-ipfs/pull/478 for more info
