### ISSUE TITLE
[RFC] Category reordering

### ISSUE THREAD

**Issue by RubenKelevra** [ipfs/awesome-ipfs#330]
I think we should reevaluate the categories, my proposal:

-Services build with IPFS somewhere in the background, as 'honorable mention', like Filecoin, Cloudflare-IPFS-Gateway etc.

-Open Source Applications/Services you can run yourself and extend the functionality of IPFS. Either accessing the API of a running daemon or running it's own implementation of IPFS.

-Datasets you can help to provide. These are static.

-Collab-Clusters which you can help to spread. Those are considered dynamic, having regular updates.

-Ressources like Videos, How-Tos, Guides, Documentations, Toolsets etc.

-News Articles (of third parties) covering IPFS directly or a specific service/application running with IPFS in the background.

_Originally posted by @RubenKelevra in https://github.com/ipfs/awesome-ipfs/issues/323#issuecomment-590937940_

**Comment by jessicaschilling** [comment]
Closing this issue to move this discussion into https://github.com/ipfs/awesome-ipfs/issues/367 - we're building a submission form for new items, and it'll include category fields.
