### ISSUE TITLE
Add Quest Messenger 

### ISSUE THREAD

**Issue by StationedInTheField** [ipfs/awesome-ipfs#357]
Please add https://github.com/QuestNetwork/quest-messenger-js 

It's a multi-platform end-to-end encrypted messenger based on ipfs.pubsub - It already works in the browser from computers and Android phones and with desktop builds on Mac and Linux.

**Comment by jessicaschilling** [comment]
@andrew, are you able to have a look? Thank you!

**Comment by andrew** [comment]
@StationedInTheField can you send a pull request to add your app to this file? https://github.com/ipfs/awesome-ipfs/blob/master/data/apps.yaml

**Comment by StationedInTheField** [comment]
Thanks!

https://github.com/ipfs/awesome-ipfs/pull/358

**Comment by andrew** [comment]
Thanks, I've merged that now 🎉
