### ISSUE TITLE
A few dead items

### ISSUE THREAD

**Issue by ColonelThirtyTwo** [ipfs/awesome-ipfs#388]
> Cooking Recipes - Around 50GB of formatted and unformatted cooking recipes. Source

This one does not seem to have any providers. `ipfs dht findprovs QmTXo6GforwsuGAd8behjgvKCsMMBdG1xMZJF4qa9W7CHB` doesn't print anything.

> Siderus Orion - Easy to use IPFS desktop client for macOS, Windows and Linux Source

This project is no longer active and the maintainer has taken it down

**Comment by CryptonightCanada** [comment]
...im back online and hope to resolve and reinstate the awesome-ipfs repository

**Comment by CryptonightCanada** [comment]
--- had an internal system crash.
 * corrupted filesystem wiped main drives out so we're working on recovering about 1tb of corrupted data and our main operating system

**Comment by ef3n9r98** [comment]
Hey @andrew, would you be willing to pay a dev to submit a PR for this issue?

**Comment by andrew** [comment]
I don’t have merge access to this repo anymore, sorry

**Comment by 2color** [comment]
Closing this as this will be resolved by #366
