### ISSUE TITLE
Readme: IPFS-FPS link seems to be dead

### ISSUE THREAD

**Issue by davidrhp** [ipfs/awesome-ipfs#394]
The IPFS-FPS link (https://ipfs-fps.com/) seems to be dead. I did a quick google search and couldn't find a replacement either (maybe I missed something though).

I found this showcasing the project ([https://showcase.ethglobal.com/hackfs/ipfs-fps](https://showcase.ethglobal.com/hackfs/ipfs-fps)), but the linked GitHub repository is down as well ([https://github.com/IPFS-FPS](https://github.com/IPFS-FPS)).

The entry should be either updated with the correct link or be removed.

**Comment by SgtPooki** [comment]
The only other thing I was able to find was an [IPFS-FPS youtube channel](https://www.youtube.com/channel/UCXpbN8bLBdaRF8YCeIZ4yoQ/featured) linked from the showcase webpage)

**Comment by defder-su** [comment]
IPFS-FPS still available in https://bafybeieyhpg2xiq7bbpluridz2sxstiufglr3r34m66rymxn2cxwbogfde.ipfs.dweb.link/.

**Comment by aschmahmann** [comment]
Seems to be resolved by #447 but feel free to reopen if you run into any issues
