### ISSUE TITLE
Feature: update danger-js to fail PRs when adding two entries

### ISSUE THREAD

**Issue by SgtPooki** [ipfs/awesome-ipfs#442]
When a contributor creates a PR that adds multiple entries, we typically block on merging the PR and require each entry to be added separately. is this a process we want to keep?

If so, we should update the danger.js file to check that only a single entry is added.

**Comment by tinytb** [comment]
What's the reason for requiring each entry to be added separately?

**Comment by SgtPooki** [comment]
> What's the reason for requiring each entry to be added separately?

That was the existing pattern. I believe it was intended to keep changes isolated and tie an owner to each added entry. I don’t feel strongly either way but prefer single/isolated additions.

**Comment by 2color** [comment]
I think we can keep it light for now. If it becomes too difficult to review and maintain PRs, we can revisit this.
