### ISSUE TITLE
"IPFS FPS" is a Virus/Spam site on front page. 

### ISSUE THREAD

**Issue by zamzx** [ipfs/awesome-ipfs#446]
Clicking on this leads to either a malicious Javascript plugin installation prompt or generic spam site.

<img width="308" alt="Screen Shot 2022-11-01 at 10 21 13 PM" src="https://user-images.githubusercontent.com/34112226/199642845-718ed651-069c-48de-b1cf-ccdbf0464d3a.png">

**Comment by aschmahmann** [comment]
Seems like it's really time to resolve/remove this. Links seem to have been dead for a while https://github.com/ipfs/awesome-ipfs/issues/394. Maintainers of the repo can decide whether they'd rather remove the link or replace it with the latest functioning CID. It's nice that things can work even when the original owner has abandoned it as long as it's somewhere, but it doesn't seem like promoting a fun example with no source code (no idea why the GH code was taken down) is a good idea so IMO it should be removed.

FYI @leon-do who seems to have filed the initial PR adding it https://github.com/ipfs/awesome-ipfs/pull/356

**Comment by leon-do** [comment]
Hey @aschmahmann 

This project has been outdated for some time. I made adjustments and now it's functional again.

CID: https://ipfs.io/ipfs/QmanBVUK5T7EgtYk6MfEtew2ji9xZvN9JcRNBejgEutZWh/

Source: https://github.com/underscoredLabs/webgl-ipfs-fps

**Comment by leon-do** [comment]
Below is an updated PR

https://github.com/ipfs/awesome-ipfs/pull/447/files

Sorry for the confusion.

**Comment by aschmahmann** [comment]
Looks to have been closed in #447. Thanks @leon-do for fixing and @zamzx for reporting.
