### ISSUE TITLE
How to talk to a site so they implement IPFS

### ISSUE THREAD

**Issue by facastagnini** [ipfs/awesome-ipfs#48]
Hi guys,

I wonder if you guys have a standard way of approaching a website so they can implement IPFS.
I am asking because I am seeing that MusicBrainz is having serious service issues and might be a good service to talk to.

Check this out https://blog.musicbrainz.org/2016/05/22/server-capacity-update/

**Comment by RichardLitt** [comment]
@facastagnini Hey, good question. We don't, really - the best thing you can do to approach musicbrainz is to email @jbenet and ask him to reach out to them. Maybe there can be some collaboration. 

In the future, this is a good question for github.com/ipfs/faq. Thanks, though!

**Comment by RichardLitt** [comment]
And, of course, you can reach out to them and show them IPFS. :D

**Comment by facastagnini** [comment]
Thanks @RichardLitt , I will try to get something done!
