### ISSUE TITLE
Implementations section?

### ISSUE THREAD

**Issue by meandavejustice** [ipfs/awesome-ipfs#488]
I opened some prs today for adding implementations #483 #487 #486 

Maybe we should just have a separate implementations section for all of these and anything else listed at https://docs.ipfs.tech/concepts/ipfs-implementations/#popular-or-actively-maintained as well as linking to it

**Comment by 2color** [comment]
The docs implementations list feels pretty comprehensive and since the docs are open source anyone can submit a PR to have it included. Maybe we can just link to it?

If we add a list here, we suddenly have two sources of truth and all the problems that come with it.
