### ISSUE TITLE
What to do with Stale projects

### ISSUE THREAD

**Issue by meandavejustice** [ipfs/awesome-ipfs#489]
Do we want to remove stale projects from the list or move them to a defunct/prior art section?

Stale projects:
- https://github.com/MichaelMure/Arbore (5 years)
- https://github.com/airsecure/airsecure (4 years) no longer in app stores
- https://github.com/RTradeLtd/ipcoronafs (3 years) gateway.temporal.cloud gateway is not reachable
- https://github.com/ipfs-search/ipfs-search deprecated/shut down
- https://github.com/hazae41/sweet-ipfs archived in 2022

**Comment by 2color** [comment]
I think if a project is stale and inactive, it takes away from its awesomeness. Maybe we can create a separate `stale.md` file where we move these links to?

**Comment by 2color** [comment]
I think if a project is stale and inactive, it takes away from its awesomeness. Maybe we can create a separate `stale.md` file where we move these links to?

**Comment by meandavejustice** [comment]
I agree, I'll move those over this evening :)
