### ISSUE TITLE
Dead link in README?

### ISSUE THREAD

**Issue by hairyhenderson** [ipfs/awesome-ipfs#50]
There's an article listed from the README:

> - [Downloading nodejs versions with nvm/n over IPFS](https://ipfs.io/ipfs/QmTkzDwWqPbnAh5YiV5VwcTLnGdwSNsNTn2aDxdXBFca7D/example#/ipfs/QmUx363UFtgiQqkHHsPK3TSDmwoALDo2hrbMWbcxjH2vFc) (ipfs.io)

It seems to be unavailable... And when I try to find `QmUx363UFtgiQqkHHsPK3TSDmwoALDo2hrbMWbcxjH2vFc` it seems to not exist...

Maybe it's a typo?

**Comment by VictorBjelkholm** [comment]
Hm, that was submitted and written by my. I'll take a look what happened.

**Comment by hairyhenderson** [comment]
Thanks! :grin:

**Comment by RichardLitt** [comment]
@victorbjelkholm word on this?

**Comment by VictorBjelkholm** [comment]
@hairyhenderson @RichardLitt sorry for the delay, completely forgot about it. Added again from source (https://gist.github.com/VictorBjelkholm/af38baab3728414ab478), hash is the same and it's available again so we can close this :)

**Comment by RichardLitt** [comment]
Thanks!

**Comment by hairyhenderson** [comment]
Thanks @VictorBjelkholm! :grin:
