### ISSUE TITLE
Add "IPFS: The Internet Democratised"

### ISSUE THREAD

**Issue by VictorBjelkholm** [ipfs/awesome-ipfs#54]
https://medium.com/@tonywillenberg/web-3-0-a-truly-democratised-internet-f4b06cb4077b is an article written about IPFS by Tony Willenberg (https://twitter.com/TonyWillenberg).

I want to add it, but not sure where. Doesn't fit under "Articles - Press" in my mind, so where would we put it?

**Comment by RichardLitt** [comment]
Why wouldn't that be press? 

Why don't we just remove the 'Press' heading, and make it just 'Articles'.

**Comment by VictorBjelkholm** [comment]
I dunno, I my head, press = mass media industry, the big guys, not a blogpost on medium. But yeah, changing it to be just articles might be better.

**Comment by RichardLitt** [comment]
Want to submit a PR?

**Comment by VictorBjelkholm** [comment]
@RichardLitt here: https://github.com/ipfs/awesome-ipfs/pull/56
