### ISSUE TITLE
Embed this list into ipfs.io website

### ISSUE THREAD

**Issue by diasdavid** [ipfs/awesome-ipfs#6]

**Comment by RichardLitt** [comment]
Working on this, have a working prototype, but I can't test it do to [this error](https://github.com/ipfs/website/issues/83).

**Comment by RichardLitt** [comment]
Fixed error. I think this looks good!

**Comment by RichardLitt** [comment]
After talking to @jbenet, I think it's better if we don't do this. I added a link to awesome-ipfs to the website, for now, which should be enough.
