### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/awesome-ipfs#61]
This link: http://whatdoesthequantsay.com/2015/09/13/ipfs-introduction-by-example/

**Comment by lidel** [comment]
Indeed, but it works without ending slash: 
http://whatdoesthequantsay.com/2015/09/13/ipfs-introduction-by-example

**Comment by VictorBjelkholm** [comment]
Fixed in 0703b25a7c6e19987cec8e4de7138a0ab6ea3d72
