### ISSUE TITLE
globalupload.io

### ISSUE THREAD

**Issue by fbonesso** [ipfs/awesome-ipfs#63]
Hello everyone!

I created a file transportation service for **IPFS**, more like an upload service I guess.

My big ambition through this project is make **IPFS** more accessible to the general public.

I'm currently working on encryption using **AES-256** and mobile version for **iOS** and **Android**.

I hope this can help in any way.

Thanks!

https://globalupload.io

**Comment by RichardLitt** [comment]
Interesting!

Why is the hash on upload.global shortened? Why not use the IPFS hash? Is there any way to know what I've uploaded, or is it just a one-off service?

**Comment by fbonesso** [comment]
Actually, at the beginning I was trying to add the file extension in the URL.

But now I change to follow the pattern of IPFS like this:

https://upload.global/ipfs/QmPPepf2GxwvWEovSWvpbA9GmhSrTWPb3d6YyHwPw4E4KA

Thanks!

**Comment by fbonesso** [comment]
But I really like the on-off service idea, this could be an option! 

I'm also planning to develop a dropbox-like sync tool.

**Comment by RichardLitt** [comment]
Cool. Add it in a PR? :)

**Comment by fbonesso** [comment]
Sure, it would be great! Thanks! :)

**Comment by RichardLitt** [comment]
@fbonesso Do you want to add it in a PR? :)

**Comment by fbonesso** [comment]
Done! :)

**Comment by lidel** [comment]
Is https://globalupload.io doing any cache warming after upload? 
(cache warming == asynchronously pre-fetching uploaded data at other IPFS nodes, eg the public gateway)

If not, you may want to join https://github.com/edrex/cachewarmer/

**Comment by fbonesso** [comment]
@lidel great idea! 

I've added the cache warming providers and an PR to use https://upload.global/ipfs/ as well!

Example:
https://upload.global/ipfs/QmPPepf2GxwvWEovSWvpbA9GmhSrTWPb3d6YyHwPw4E4KA
https://ipfs.io/ipfs/QmPPepf2GxwvWEovSWvpbA9GmhSrTWPb3d6YyHwPw4E4KA
https://xmine128.tk/ipfs/QmPPepf2GxwvWEovSWvpbA9GmhSrTWPb3d6YyHwPw4E4KA

Thanks!

**Comment by lidel** [comment]
Cool!  :rocket: 
Last cosmetic thing: https://upload.global/ returns 404, but you probably want  to redirect main page to https://globalupload.io

**Comment by fbonesso** [comment]
Sure! 

https://upload.global/ and https://upload.global/ipfs/

Thanks again! 😄

**Comment by VictorBjelkholm** [comment]
Since globalupload.io now have been added to the list, I'll close this issue
