### ISSUE TITLE
All the ethereum+ipfs apps/platforms

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/awesome-ipfs#65]
None of the apps/companies mentioned in @jbenet's [devcon2 talk](https://youtu.be/Itb_2EMgBUI?t=9m55s) (uPort, mediachain, akasha, openbazaar, etc.) are listed in this repo.  They should all be added.

**Comment by siddharthist** [comment]
@flyingzumwalt Doesn't seem like anyone's jumped on this. Want to open a PR?

**Comment by flyingzumwalt** [comment]
@RichardLitt what do you want to do about this? Are we actively maintaining awesome-ipfs or are we leaning towards moving to a different approach?

**Comment by RichardLitt** [comment]
@flyingzumwalt We are; I or @VictorBjelkholm tend to respond to PRs within a couple of days. Normally, the person who opens an issue on an open source list like this is the person who is expected to open the PR (as @siddharthist pointed out, too). Do you not want to open a PR?

**Comment by RichardLitt** [comment]
I found these, but wasn't able to find good links for the others:

[uport](https://uport.me/#home) - Uport is a mobile, self-sovereign identity and key management system, built on the Ethereum blockchain.
[akaska](http://akasha.world/) - A Next-Generation Social Media Network, powered by ethereum and embedded into IPFS
[digx](https://www.dgx.io/) - Digix is an asset-tokenisation platform built on Ethereum and IPFS.
[dapple](https://github.com/nexusdev/dapple) - Dapple is a Solidity developer multitool designed to manage the growing complexity of interconnected smart contract systems.
[ujo](http://ujomusic.com/) - A blockchain marketplace for musicians
