### ISSUE TITLE
Find a better way to track and feature great IPFS-based work

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/awesome-ipfs#66]
There is amazing ipfs-based work cropping up all the time. This repository is barely catching any of it.  It isn't even capturing the [most prominent work](https://github.com/ipfs/awesome-ipfs/issues/65), despite the fact that the IPFS maintainers are very aware of that work and @jbenet is featuring that work in his presentations.

I think this is a sign that we're using the wrong approach to gather this information and keep it up to date. We should reconsider the whole thing in order to figure out the best process for featuring great ipfs-based work and allowing people to get their work featured.

Do people have ideas about what would be the right tool to keep a robust list of ipfs-based work, apps, tools and platforms?

It should
- Aim to toward comprehensiveness -- we want to know how many people are building stuff on IPFS, and what they are building
- Allow people to submit their work for inclusion in the list
- Allow maintainers/moderators to feature especially impressive or exciting work
- Have links back to the work itself and include ways to find the work's maintainers
- Allow us to categorize different work -- ie. "Social Platforms and Messaging Applications", "Media Platforms", "Archiving", "File Sharing", etc. or "IPFS+Ethereum", "Distributed Apps", etc.

We should also prominently display the "featured" work in multiple places with links and instructions for submitting your own work.

**Comment by RichardLitt** [comment]
I agree with the sentiment of this, entirely. It may be worthwhile to take the opportunity to plan for a larger app - not just a Markdown file in a repository, but something more like a website that can capture these things. Markdown doesn't allow filtering, and is prohibitive in terms of media (videos, large pictures).

**Comment by lidel** [comment]
@mikeal would it make sense for Community WG to take over the maintenance of this repo?

**Comment by flyingzumwalt** [comment]
That makes sense to me, especially since the quality and completeness of the info in this repo affects the ease of the Community WG's work. Maintenance of this list also falls partially under @parkan's work

**Comment by koalalorenzo** [comment]
Is the Community WG something that we can help with?
