### ISSUE TITLE
simple webapps

### ISSUE THREAD

**Issue by jbenet** [ipfs/awesome-ipfs#7]
i like making simple single-page apps that are tools that need no servers.

examples: https://github.com/ipfs/examples/tree/master/webapps

need more

**Comment by jbenet** [comment]
btw, @davidar you may want to help curate this list, you have a good picture into many of the areas of the project

**Comment by VictorBjelkholm** [comment]
Awesome! Simple to make, simple to use :)

Something that makes those examples a bit to simple though, is that allow content consumption but not content creation. Worth thinking about how/if we can make them able to create content as well as consume it.

**Comment by davidar** [comment]
@jbenet Yeah, I keep meaning to put stuff into this list. I should probably do it as I think of/come across things :)

@VictorBjelkholm The dropin replacement for dropbox.js should make it a lot easier to start porting existing content-creation webapps to ipfs (markup.rocks, stackedit.io, etc)

**Comment by RichardLitt** [comment]
I added the webapps mentioned; hopefully, this will spur other people on to add more.

**Comment by harlantwood** [comment]
The dataviz tree app would be good to add as well... Related to https://github.com/ipfs/dataviz/issues/8
