### ISSUE TITLE
Moar articles?

### ISSUE THREAD

**Issue by RichardLitt** [ipfs/awesome-ipfs#8]
There should be more! @sindresorhus asked for some more when this [was added](https://github.com/sindresorhus/awesome/pull/394) to the [main awesome list](https://github.com/sindresorhus/awesome).

**Comment by VictorBjelkholm** [comment]
Two more that can be added:

*
http://motherboard.vice.com/read/the-interplanetary-file-system-wants-to-create-a-permanent-web
*
https://hacked.com/first-steps-toward-implementing-distributed-permanent-web-ipfs/

Unable to add them myself right now

Sincerely,
Victor Bjelkholm
(+34) 672 15 90 89

**Comment by RichardLitt** [comment]
PRed. Thanks @VictorBjelkholm!
